### PR TITLE
update to latest schema jar

### PR DESCRIPTION
**Pull request by mrcnc**
## Status
**READY**

## Description
This upgrades the sdk to use the latest schema jar.  It also refactors the build to pull this jar from the boundless maven repo instead of packaging within the sdk

### CODE REVIEW

**Comment by mrcnc** [comment]
Probably should coordinate this update with spatialconnect-ios-sdk as well

**Comment by joshkendrick** [comment]
LGTM

**Review by joshkendrick — APPROVED** [review]
Bumping the version number is probably right, we'll need to bump react-native-sc, etc on down the line as well.

**Comment by tetriscode** [comment]
iOS is ready

**Comment by mrcnc** [comment]
iOS PR: https://github.com/boundlessgeo/spatialconnect-ios-sdk/pull/191/files

**Comment by mrcnc** [comment]
Also related: https://github.com/boundlessgeo/react-native-spatialconnect/pull/18/files#diff-7ae5a9093507568eabbf35c3b0665732R55

**Pull request merged**
